#include "pc_midday_animation_stage.h"
#include <cstdio>
#include <cstring>
using namespace pc_midday;
namespace {int checks=0,failed=0;void check(bool v,const char*s){++checks;if(!v){++failed;std::printf("FAIL %s\n",s);}}
u32 bits(float f){u32 value;std::memcpy(&value,&f,4);return value;}
struct Resolver:LogicalResolver {int data=9,calls=0;bool deny=false,unbound=false;
 bool identify(const char*,RefKind,const void*,LogicalRef&,std::string&)override{return false;}
 bool validate(const char*k,RefKind role,const LogicalRef&r,std::string&)const override{return std::string(k)=="context.data"&&role==RefKind::Animation&&!r.owner&&!r.slot&&(!r.resource||r.resource==10);}
 bool validateTyped(const FieldSchema&s,const LogicalRef&r,std::string&e)const override{return !deny&&s.targetType=="AnimData"&&s.ownership==ReferenceOwnership::Content&&validate(s.key.c_str(),s.reference,r,e);}
 bool resolve(const char*k,RefKind role,const LogicalRef&r,void*&p,std::string&e)override{++calls;if(unbound||!validate(k,role,r,e))return false;p=r.resource?&data:nullptr;return true;}
 bool identifyHandle(const char*,RefKind,u32,LogicalRef&,std::string&)override{return false;}
 bool resolveHandle(const char*,RefKind,const LogicalRef&,u32&,std::string&)override{return false;}
};}
int main(){Resolver resolver;AnimationContentIndex index;std::string e;check(index.declare({0,10,0},32,e),"compiled clip metadata");auto content=[&](const LogicalRef&r,float frame,std::string&e){return index.validate(r,frame,e);};auto factory=[&](u64 id)->LogicalResolver*{return id>=1&&id<=3?&resolver:nullptr;};
 ActorBytes active,empty;check(encodeAnimationContext({{0,10,0},32,-0.0f},resolver,content,active,e),"terminal native animation frame descriptor");check(encodeAnimationContext({{},0,30},resolver,content,empty,e),"constructor context descriptor");std::vector<CanonicalContextRecord> records{{2,active},{1,active},{3,empty}};std::vector<PlannedContext> plan;
 check(planCanonicalContexts(records,{1,2,3},factory,content,plan,e)&&plan.size()==3,"exact canonical inventory");check(resolver.calls==2,"shared immutable clip resolved once per context before native writes");void*a=nullptr,*b=nullptr;check(plan[0].pointers.resolve("context.data",RefKind::Animation,{0,10,0},a,e)&&plan[1].pointers.resolve("context.data",RefKind::Animation,{0,10,0},b,e)&&a==b&&a==&resolver.data&&resolver.calls==2,"shared data alias pinned");check(bits(plan[0].state.speed)==0x80000000&&plan[0].state.frame==32,"terminal frame and negative-zero speed preserved");
 auto bad=records;bad[1].id=2;check(!planCanonicalContexts(bad,{1,2,3},factory,content,plan,e)&&plan.size()==3,"duplicate canonical ID refuses transactionally");bad=records;bad[1].id=0;check(!planCanonicalContexts(bad,{1,2,3},factory,content,plan,e),"zero ID refused");bad=records;bad[1].id=4;check(!planCanonicalContexts(bad,{1,2,3},factory,content,plan,e),"foreign ID refused");bad=records;bad.pop_back();check(!planCanonicalContexts(bad,{1,2,3},factory,content,plan,e),"missing context refuses instead of default reset");check(!planCanonicalContexts(records,{0,1,2,3},factory,content,plan,e),"invalid required inventory refused");check(!planCanonicalContexts(records,{1,2,3},{},content,plan,e),"no resolver factory refused");check(!planCanonicalContexts(records,{1,2,3},factory,{},plan,e),"no clip validator refused");auto unavailable=[](u64)->LogicalResolver*{return nullptr;};check(!planCanonicalContexts(records,{1,2,3},unavailable,content,plan,e),"missing concrete resolver refused");bad=records;bad[0].payload.pop_back();check(!planCanonicalContexts(bad,{1,2,3},factory,content,plan,e),"truncated payload refused");resolver.deny=true;check(!planCanonicalContexts(records,{1,2,3},factory,content,plan,e),"typed role refusal");resolver.deny=false;resolver.unbound=true;check(!planCanonicalContexts(records,{1,2,3},factory,content,plan,e),"unbound content refuses before native allocation");resolver.unbound=false;check(planCanonicalContexts({}, {},factory,content,plan,e)&&plan.empty(),"legitimately empty authoritative inventory");
 std::printf("%d checks, %d failures\n",checks,failed);return failed?1:0;}
