#include "pc_p2_original_captain_cstick.h"
#include <fstream>
#include <iterator>
#include <iostream>
#include <stdexcept>
#include <limits>
#include <cmath>
using namespace p2original::captain;namespace cs=cstick;
namespace {unsigned checks=0;std::string error;
void check(bool yes,const char* name){++checks;if(!yes)throw std::runtime_error(std::string(name)+": "+error);}
bool near(float a,float b){return std::fabs(a-b)<.0001f;}
cs::Input input(){cs::Input f;f.camera.side={1,1,0};f.camera.up={0,1,0};f.camera.view={0,0,1};f.targetVelocity=cs::Vec3{};f.sourceState=StateId::Walk;f.plateAngle=0;f.slotCount=2;return f;}
cs::AfterRefresh census(float distance){cs::AfterRefresh f;actions::PikiFrame member;member.handle={reinterpret_cast<Piki*>(1),10};member.position={0,distance,0};f.members.push_back(member);f.maxPositionOffset=cs::Vec3{10,20,0};return f;}
}
int main(int argc,char** argv){try{
 check(argc==2,"actual private Navi parameter argument");std::ifstream f(argv[1],std::ios::binary);std::string bytes((std::istreambuf_iterator<char>(f)),{});cs::Parameters parameters;check(cs::parseParameters(bytes,parameters,error),"authentic source parameter parser");check(parameters.waitRange()==15&&parameters.changeRange()==40,"actual p039/p040 bytes");
 auto changed=bytes;changed[0]^=1;check(!cs::parseParameters(changed,parameters,error)&&parameters.authenticated(),"raw byte mutation rejected without changing previous output");
 cs::Parameters empty;cs::State state;cs::Plan plan;plan.resetSceneAnimationTimer=true;auto in=input();check(!cs::prepare(empty,in,state,plan,error)&&plan.resetSceneAnimationTimer,"unauthenticated policy preserves output");
 cs::onInit(state);check(state.scaleTimer==0&&state.angle==0&&!state.neutralTurn&&!state.needRearrange&&!state.distanceState&&!state.increment&&!state.commandOn1,"literal onInit only initializes source-assigned fields");
 check(!cs::prepare(parameters,in,state,plan,error)&&plan.resetSceneAnimationTimer,"unknown _2FC neutral read refuses");
 in.controller=true;in.stickY=1;check(!cs::prepare(parameters,in,state,plan,error),"missing MoviePlayer authority only when controller reads it");in.demoInactive=true;
 check(cs::prepare(parameters,in,state,plan,error),"active establishes source flags without reading undefined distance fields");check(plan.commands.size()==2&&plan.commands[0].kind==cs::CommandKind::Refresh&&plan.commands[0].strength==1&&plan.commands[1].kind==cs::CommandKind::SetPos,"active source refresh-before-setPos");check(plan.state.scaleTimer==1&&plan.state.neutralTurn==0&&plan.state.commandOn1==false&&plan.state.commandOn2==true&&!plan.state.needRearrange&&!plan.state.distanceState,"active only assigns actual source fields");check(plan.resetSceneAnimationTimer&&plan.state.position->z==1&&plan.state.targetVector->z==1,"actual source command and timer reset");
 state=plan.state;for(int i=0;i<38;++i){check(cs::prepare(parameters,in,state,plan,error),"active saturation progression");state=plan.state;}check(state.scaleTimer==39&&plan.commands.back().scale==1,"39 frames retains scale1");check(cs::prepare(parameters,in,state,plan,error)&&plan.state.scaleTimer==40&&plan.commands.back().scale==3,"40 frames scale3");state=plan.state;check(cs::prepare(parameters,in,state,plan,error)&&plan.state.scaleTimer==40,"scale timer saturates at40");
 auto neutral=input();check(cs::prepare(parameters,neutral,state,plan,error)&&plan.neutral&&plan.commands.size()==2&&plan.commands[0].kind==cs::CommandKind::SetPos&&plan.commands[1].kind==cs::CommandKind::Refresh,"neutral retained-angle setPos precedes refresh");cs::Plan suffix;suffix.resetSceneAnimationTimer=true;check(!cs::completeNeutral(parameters,*plan.neutral,census(10),suffix,error)&&suffix.resetSceneAnimationTimer,"unknown CStickState only refuses when post-refresh branch reads it");
 state.distanceState=2;state.increment.reset();check(cs::prepare(parameters,neutral,state,plan,error)&&cs::completeNeutral(parameters,*plan.neutral,census(14.999f),suffix,error),"mismatched distance state establishes unknown counter");check(suffix.state.distanceState==0&&suffix.state.increment==0&&suffix.state.needRearrange==1&&suffix.commands.empty(),"near mode literal state/flag writes");
 state=suffix.state;state.increment.reset();check(cs::prepare(parameters,neutral,state,plan,error)&&!cs::completeNeutral(parameters,*plan.neutral,census(10),suffix,error),"matching state unknown increment refuses");state.increment=4;
 check(cs::prepare(parameters,neutral,state,plan,error)&&cs::completeNeutral(parameters,*plan.neutral,census(10),suffix,error)&&suffix.state.increment==5,"matching state source counter increments");
 check(cs::completeNeutral(parameters,*plan.neutral,census(15),suffix,error)&&suffix.state.distanceState==1&&suffix.commands.size()==1&&suffix.commands[0].kind==cs::CommandKind::SetPosGray&&near(suffix.commands[0].angle,1.5707963f),"strict authored wait boundary uses gray maxPositionOffset");
 auto missing=census(15);missing.maxPositionOffset.reset();check(!cs::completeNeutral(parameters,*plan.neutral,missing,suffix,error),"gray branch requires genuine post-refresh max offset");
 check(cs::completeNeutral(parameters,*plan.neutral,census(40),suffix,error)&&suffix.state.distanceState==2&&suffix.commands.size()==2&&suffix.commands[0].kind==cs::CommandKind::Rearrange&&suffix.commands[1].kind==cs::CommandKind::SetPos&&suffix.state.needRearrange==0&&!(*suffix.state.commandOn1),"strict change boundary rearranges then normal setPos");
 state=suffix.state;check(cs::prepare(parameters,neutral,state,plan,error)&&cs::completeNeutral(parameters,*plan.neutral,{},suffix,error)&&suffix.commands.size()==1&&suffix.commands[0].kind==cs::CommandKind::SetPos,"empty fullPlate uses12800 and no repeated rearrangement");
 state.needRearrange.reset();check(cs::prepare(parameters,neutral,state,plan,error)&&!cs::completeNeutral(parameters,*plan.neutral,census(40),suffix,error),"far branch unknown _2FD refuses");
 state.needRearrange=1;state.distanceState=0;state.increment=0;neutral.targetVelocity=cs::Vec3{0,50,0};check(cs::prepare(parameters,neutral,state,plan,error)&&plan.commands.size()==1&&plan.commands[0].kind==cs::CommandKind::Refresh&&plan.state.neutralTurn==1,"whole target velocity vertical50 skips retained setPos");
 neutral.targetVelocity=cs::Vec3{0,49.999f,0};check(cs::prepare(parameters,neutral,state,plan,error)&&plan.commands.size()==2,"strict target speed below50 retains angle");neutral.sourceState=StateId::ThrowWait;check(cs::prepare(parameters,neutral,state,plan,error)&&plan.commands.size()==1&&plan.state.neutralTurn==1,"source ThrowWait exclusion");
 neutral.sourceState.reset();check(!cs::prepare(parameters,neutral,state,plan,error),"neutral slow branch requires actual source state");neutral.targetVelocity=cs::Vec3{0,50,0};check(cs::prepare(parameters,neutral,state,plan,error),"speed50 short-circuit never reads missing state");
 state.neutralTurn=1;state.angle.reset();neutral.targetVelocity.reset();check(cs::prepare(parameters,neutral,state,plan,error)&&plan.commands.size()==1,"already turned branch does not read angle/target velocity");
 auto full=census(100);auto nearest=census(1).members[0];nearest.handle={reinterpret_cast<Piki*>(2),20};nearest.state=actions::PikiState::Unsupported;nearest.throwable=false;full.members.push_back(nearest);check(cs::completeNeutral(parameters,*plan.neutral,full,suffix,error)&&suffix.state.distanceState==0,"nearest fullPlate includes nonthrowable unsupported-state physical member");
 full.members.push_back(nearest);check(!cs::completeNeutral(parameters,*plan.neutral,full,suffix,error),"duplicate exact census handle refuses");
 state.neutralTurn=0;state.angle=0;state.distanceState=0;state.increment=std::numeric_limits<int>::max();neutral=input();check(cs::prepare(parameters,neutral,state,plan,error)&&!cs::completeNeutral(parameters,*plan.neutral,census(1),suffix,error),"signed source increment overflow explicit refusal");
 cs::onInit(state);in=input();in.controller=true;in.demoInactive=true;in.stickY=.05f;state.neutralTurn=1;check(cs::prepare(parameters,in,state,plan,error)&&plan.neutral&&!plan.resetSceneAnimationTimer,"exact .05 transformed magnitude neutral");in.stickY=.050001f;check(cs::prepare(parameters,in,state,plan,error)&&!plan.neutral&&plan.resetSceneAnimationTimer,"strict above .05 active");
 in.stickY=.4775f;check(cs::prepare(parameters,in,state,plan,error)&&near(plan.commands[0].strength,.3f),"source normalized strength .45 to .3");in.stickY=.905f;check(cs::prepare(parameters,in,state,plan,error)&&plan.commands[0].strength==1,"normalized .9 hard saturation");
 in.stickY=1;in.plateAngle=1.57079632679f;check(cs::prepare(parameters,in,state,plan,error)&&near(*plan.state.angle,.9424778f),"less-than120-degree angle interpolates .4 toward stick");in.plateAngle=3.14159265359f;check(cs::prepare(parameters,in,state,plan,error)&&near(*plan.state.angle,0),"opposed plate bypasses interpolation");
 in=input();in.controller=true;in.demoInactive=true;in.stickX=1;in.plateAngle=1.57079632679f;check(cs::prepare(parameters,in,state,plan,error)&&plan.state.position->x==-1&&near(*plan.state.angle,4.712389f),"actual negative hardware X and angle wrap");
 in.demoInactive=false;in.stickX=std::numeric_limits<float>::quiet_NaN();check(cs::prepare(parameters,in,state,plan,error)&&plan.neutral,"playing movie never reads sub-stick values");
 in=input();in.camera.side={};in.camera.view={};state.neutralTurn=1;check(cs::prepare(parameters,in,state,plan,error)&&plan.neutral,"source zero horizontal camera normalization keeps zero");
 in=input();in.camera.up={0,0,1};in.camera.view={0,1,0};in.controller=true;in.demoInactive=true;in.stickY=1;check(cs::prepare(parameters,in,state,plan,error)&&plan.state.position->z==1,"actual camera up chosen by vertical comparison");
 std::cout<<checks<<" literal source C-stick/plate controls PASS (policy; no gameplay claim)\n";return 0;
 }catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
